BEGIN TRANSACTION;
INSERT INTO "Cars"(Id,Name,Price) VALUES(1,'Audi',52642);
INSERT INTO "Cars"(Id,Name,Price) VALUES(2,'Mercedes',57127);
INSERT INTO "Cars"(Id,Name,Price) VALUES(3,'Skoda',9000);
INSERT INTO "Cars"(Id,Name,Price) VALUES(4,'Volvo',29000);
INSERT INTO "Cars"(Id,Name,Price) VALUES(5,'Bentley',350000);
INSERT INTO "Cars"(Id,Name,Price) VALUES(6,'Citroen',21000);
INSERT INTO "Cars"(Id,Name,Price) VALUES(7,'Hummer',41400);
INSERT INTO "Cars"(Id,Name,Price) VALUES(8,'Volkswagen',21600);
COMMIT;
